sudo: require
services:
  - docker

before_install:
  - docker build -t hungbui7690/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true hungbui7690/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'docker'
  env: 'docker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-484992977674'
  bucket_path: 'docker'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
